package com.klikli_dev.occultism.datagen.book.getting_started;

import com.klikli_dev.modonomicon.api.datagen.CategoryProvider;
import com.klikli_dev.modonomicon.api.datagen.EntryBackground;
import com.klikli_dev.modonomicon.api.datagen.EntryProvider;
import com.klikli_dev.modonomicon.api.datagen.book.BookIconModel;
import com.klikli_dev.modonomicon.api.datagen.book.page.BookSpotlightPageModel;
import com.klikli_dev.modonomicon.api.datagen.book.page.BookTextPageModel;
import com.klikli_dev.modonomicon.api.datagen.book.page.BookCraftingRecipePageModel;
import com.klikli_dev.modonomicon.client.gui.book.theme.GuiSprite;
import com.klikli_dev.occultism.registry.OccultismBlocks;
import net.minecraft.world.item.crafting.Ingredient;

public class SpiritAttunedCrystalEntry extends EntryProvider {

    public static final String ENTRY_ID = "spirit_attuned_crystal";

    public SpiritAttunedCrystalEntry(CategoryProvider parent) {
        super(parent);
    }

    @Override
    protected void generatePages() {
        this.page("spotlight", () -> BookSpotlightPageModel.create()
                .withItem(Ingredient.of(OccultismBlocks.SPIRIT_ATTUNED_CRYSTAL.get()))
                .withText(this.context().pageText()));
        this.pageText("A rare crystal found in underground groves, used as a high-tier crafting component in many recipes such as stabilizers, dimensional machines, miners, and more.\n");

        this.page("crafting", () -> BookCraftingRecipePageModel.create()
                .withRecipeId1(this.modLoc("crafting/spirit_attuned_crystal"))
                .withText(this.context().pageText()));
        this.pageText("Spirit Attuned Crystals are crafted from their natural form using a ritualistic process.\n");

        this.page("location", () -> BookTextPageModel.create()
                .withTitle(this.context().pageTitle())
                .withText(this.context().pageText()));
        this.pageTitle("Where to find");
        this.pageText("Spirit Attuned Crystals are generated by the underground grove worldgen feature. They can be found deep underground in these rare grove formations.\n");
    }

    @Override
    protected String entryName() {
        return "Spirit Attuned Crystal";
    }

    @Override
    protected String entryDescription() {
        return "Rare crystal for high-tier crafting";
    }

    @Override
    protected GuiSprite entryBackground() {
        return EntryBackground.DEFAULT;
    }

    @Override
    protected BookIconModel entryIcon() {
        return BookIconModel.create(OccultismBlocks.SPIRIT_ATTUNED_CRYSTAL.get());
    }

    @Override
    protected String entryId() {
        return ENTRY_ID;
    }
}
