pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'Occultism ' + minecraft_version

//def localLibraryPath = file('../code-defined-gui')
//if (localLibraryPath.exists()) {
//    println "Using local composite build for code-defined-gui"
//    includeBuild(localLibraryPath) {
//        dependencySubstitution {
//            substitute module("com.klikli_dev:codedefinedgui-${minecraft_version}-neoforge:${code_defined_gui_version}") using project(':')
//        }
//    }
//}
