package com.klikli_dev.occultism.datagen.book.binding_rituals;

import com.klikli_dev.modonomicon.api.datagen.CategoryProvider;
import com.klikli_dev.modonomicon.api.datagen.EntryBackground;
import com.klikli_dev.modonomicon.api.datagen.EntryProvider;
import com.klikli_dev.modonomicon.api.datagen.book.BookIconModel;
import com.klikli_dev.modonomicon.api.datagen.book.page.BookSpotlightPageModel;
import com.klikli_dev.modonomicon.api.datagen.book.page.BookTextPageModel;
import com.klikli_dev.modonomicon.client.gui.book.theme.GuiSprite;
import com.klikli_dev.occultism.integration.modonomicon.pages.BookRitualRecipePageModel;
import com.klikli_dev.occultism.registry.OccultismBlocks;
import net.minecraft.ChatFormatting;
import net.minecraft.world.item.crafting.Ingredient;

public class DimensionalExtractorEntry extends EntryProvider {

    public static final String ENTRY_ID = "dimensional_extractor";


    public DimensionalExtractorEntry(CategoryProvider parent) {
        super(parent);
    }

    @Override
    protected void generatePages() {
        this.page("spotlight", () -> BookSpotlightPageModel.create()
                .withItem(Ingredient.of(OccultismBlocks.DIMENSIONAL_EXTRACTOR.asItem()))
                .withText(this.context().pageText()));
        this.pageText("""
                         The dimensional extractor contains a {0} that quickly collects
                          resources generated by dimensional machines or worker spirits
                          and transfers the results to an inventory below.
                        """,
                this.color("Djinni", ChatFormatting.DARK_PURPLE)
        );

        this.page("ritual", () -> BookRitualRecipePageModel.create()
                .withRecipeId1(this.modLoc("ritual/craft_dimensional_extractor"))
        );
        //no text

        this.page("use", () -> BookTextPageModel.create()
                .withTitle(this.context().pageTitle())
                .withText(this.context().pageText()));
        this.pageTitle("Using");
        this.pageText("""
                 It's very simple to use: just place your machines/spirits on top of it
                  and connect an inventory directly below that accepts items from the top side.
                  \\
                  NOTE: If the inventory is full, the djinn will simply discard the excess items.
                """
        );
    }

    @Override
    protected String entryName() {
        return "Dimensional Extractor";
    }

    @Override
    protected String entryDescription() {
        return "Enable auto-output";
    }

    @Override
    protected GuiSprite entryBackground() {
        return EntryBackground.DEFAULT;
    }

    @Override
    protected BookIconModel entryIcon() {
        return BookIconModel.create(OccultismBlocks.DIMENSIONAL_EXTRACTOR.asItem());
    }

    @Override
    protected String entryId() {
        return ENTRY_ID;
    }
}
