# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/klikli-dev/occultism/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "${mod_id}" #mandatory
# The version number of the mod
version = "${mod_version}" #mandatory
# A display name for the mod
displayName = "${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL = "https://raw.githubusercontent.com/klikli-dev/occultism/meta/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://www.curseforge.com/minecraft/mc-mods/occultism" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "occultism.png" #optional
# A text field displayed in the mod UI
credits = """See https://github.com/klikli-dev/occultism#licensing""" #optional
# A text field displayed in the mod UI
authors = "${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''${mod_description}'''

[[mixins]]
config="occultism.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "modonomicon"
type = "required"
versionRange = "[${modonomicon_version},)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "codedefinedgui"
type = "required"
versionRange = "[${code_defined_gui_version},)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "theurgy"
type = "optional"
versionRange = "[${theurgy_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "required"
versionRange = "[${curios_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "almostunified"
type = "optional"
versionRange = "[${almost_unified_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "emi"
type = "optional"
versionRange = "[${emi_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "apothic_enchanting"
type = "optional"
versionRange = "[${apothic_enchanting_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "create"
type = "optional"
versionRange = "[6.0.0,)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "immersiveengineering"
type = "optional"
versionRange = "[12.1.0-185,)"
side = "BOTH"
